#!/usr/bin/env bash

# set -x
set -e

source ./shell/functions

# 1. Diff so fancy

PACKAGE="diff-so-fancy"
install_brew_package_if_needed "$PACKAGE"

# 2. ZSH

CURRENT_DIR=$(pwd)

# Using oh-my-zsh
OH_MY_ZSH_INSTALL_SCRIPT_URL="https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"

export ZSH="$CURRENT_DIR/oh-my-zsh"

sh -c "$(curl -fsSL $OH_MY_ZSH_INSTALL_SCRIPT_URL)" 
