#!/usr/bin/env zsh 

echo "Installing VS code extensions from 'vscode-extensions.txt'..."

if [ "$1" = "export" ]; then
	if [ -f .vscode-extensions.txt ]; then		
		read -p ".vscode-extensions.txt already exists. Do you want to overwrite? (y/n): " confirm

		if [ "$confirm" != "y" ]; then
			echo "Export canceled."
			exit 0
		fi
	fi
	
	code --list-extensions > .vscode-extensions.txt
	echo "\n\U2705 Extensions successfully exported to .vscode-exsentions.txt"
elif [ "$1" = "install" ]; then
 	if [ ! -f .vscode-extensions.txt ]; then
 		echo ".vscode-extensions.txt not found. Please make sure that extensions are exported into a file before installing"
 		exit 1
 	fi
	
 	cat .vscode-extensions.txt | xargs -L 1 code --install-extensions
 	echo "\n\U2705 Extensions installed successfully.\n"
 else
	echo "\n\U1F7E1 Argument missing!"
 	echo "\U1F449 Usage: $0 { export | instsall }\n"
fi
